IF EXISTS
(
    SELECT TOP 1
           s.SPECIFIC_NAME
    FROM INFORMATION_SCHEMA.ROUTINES s
    WHERE s.ROUTINE_TYPE = 'PROCEDURE'
          AND s.ROUTINE_NAME = 'USP_CAMPANIA_SEARCH'
)
BEGIN
    DROP PROC [dbo].[USP_CAMPANIA_SEARCH];
END;
GO
/*
USP_CAMPANIA_SEARCH '01'
GO
USP_CAMPANIA_SEARCH '01','ASDA'
*/
CREATE PROCEDURE [dbo].[USP_CAMPANIA_SEARCH]
    @CODCIA CHAR(2),
    @SEARCH VARCHAR(200) = NULL
WITH ENCRYPTION
AS
SET NOCOUNT ON;

SELECT c.IDCAMPANIA AS 'ide',
       c.NOMBRE AS 'nom',
       CONVERT(VARCHAR(10),c.FECHAINICIO,103) AS 'ini',
       CONVERT(VARCHAR(10),c.FECHAFIN,103) AS 'fin',
	   CASE c.ACTIVO WHEN 1 THEN 'SI' ELSE 'NO' END AS 'activo',
       c.MONTO AS 'monto'
FROM dbo.CAMPANIA c
WHERE c.CODCIA = @CODCIA
      AND c.NOMBRE LIKE '%' + @SEARCH + '%'
      OR @SEARCH IS NULL;

GO