ALTER TABLE dbo.VEMAEST ADD VEM_BREVETE VARCHAR(10);
ALTER TABLE dbo.VEMAEST ADD VEM_PLACA VARCHAR(10);
ALTER TABLE dbo.VEMAEST ADD VEM_CAPACIDAD_KG INT;
ALTER TABLE dbo.PEDIDO ADD idRepartidor INT DEFAULT NULL;