IF EXISTS ( SELECT TOP 1
                    S.SPECIFIC_NAME
            FROM    information_schema.routines s
            WHERE   s.ROUTINE_TYPE = 'PROCEDURE'
                    AND S.ROUTINE_NAME = 'USP_REPARTO_LOADUSUARIOS' )
    BEGIN
        DROP PROC [dbo].[USP_REPARTO_LOADUSUARIOS]
    END
GO
/*
USP_REPARTO_LOADUSUARIOS '01'
*/
CREATE PROCEDURE [dbo].[USP_REPARTO_LOADUSUARIOS]
@CODCIA CHAR(2)
WITH ENCRYPTION
AS
SET NOCOUNT ON

--REPARTIDORES
SELECT '-1' AS 'COD','.: SELECCIONE :.' AS 'NOM',0 AS 'CAP'
UNION
SELECT v.VEM_CODVEN AS 'COD',RTRIM(LTRIM(v.VEM_NOMBRE)) AS 'NOM',v.VEM_CAPACIDAD_KG AS 'CAP'
FROM dbo.VEMAEST v WHERE v.VEM_CODCIA=@CODCIA AND v.VEM_IDPERFIL = 3
ORDER BY 2

--VENDEDORES
SELECT '-1' AS 'COD','.: SELECCIONE :.' AS 'NOM'
UNION
SELECT v.VEM_CODVEN AS 'COD',RTRIM(LTRIM(v.VEM_NOMBRE)) AS 'NOM' 
FROM dbo.VEMAEST v WHERE v.VEM_CODCIA=@CODCIA AND v.VEM_IDPERFIL = 2
ORDER BY 2

GO