IF EXISTS
(
    SELECT TOP 1
           s.SPECIFIC_NAME
    FROM INFORMATION_SCHEMA.ROUTINES s
    WHERE s.ROUTINE_TYPE = 'PROCEDURE'
          AND s.ROUTINE_NAME = 'USP_TICKET_SYNC'
)
BEGIN
    DROP PROC [dbo].[USP_TICKET_SYNC];
END;
GO
/*
USP_TICKET_SYNC
*/
CREATE PROCEDURE [dbo].[USP_TICKET_SYNC]
WITH ENCRYPTION
AS
SET NOCOUNT ON;

/*
SELECT * FROM dbo.TICKET t
SELECT * FROM DBSRVHIELOSCLOUD.dbo.TICKET t
SELECT rucEmisor FROM OPENQUERY(TICKETS, 'select RUCEMISOR from TICKET where idempresa = 1')
*/

DECLARE @tsql VARCHAR(4000),
        @openquery VARCHAR(4000),
        @linkedserver VARCHAR(20),
        @insertquery VARCHAR(4000),
        @tsql2 VARCHAR(4000),
		@tsqlI1 VARCHAR(4000),
		@tsqlI2 VARCHAR(4000);
DECLARE @MIN INT, @MAX INT;
DECLARE @IDTICKET BIGINT,@IDCAMPANIA INT, @RUCEMISOR VARCHAR(11), @FECHAEMISION DATE, @TIPOCOMPROBANTE CHAR(1), @SERIECOMPROBANTE VARCHAR(3),@NUMEROCOMPROBANTE BIGINT,
		@CODIGOCLIENTE BIGINT,@NUMEROTICKET VARCHAR(20);

DECLARE @TBLTICKET TABLE
(
    IDTICKET BIGINT,
	IDCAMPANIA INT,
	RUCEMISOR VARCHAR(11),
	FECHAEMISION DATE,
	TIPO CHAR(1),
	SERIE VARCHAR(3),
	NUMERO BIGINT,
	CODIGOCLIENTE BIGINT,
	NUMEROTK VARCHAR(20),
	INDICE INT IDENTITY
);
DECLARE @TBLVALIDA TABLE(RUCEMISOR VARCHAR(11))


--OBTENIENDO LA EMPRESA POR DEFECTO - inicio
DECLARE @IDEMPRESA INT;
SELECT TOP 1
       @IDEMPRESA = e.IdEmpresa
FROM dbo.EMPRESA e
WHERE e.Activo = 1
      AND e.Defecto = 1;
--OBTENIENDO LA EMPRESA POR DEFECTO - fin



INSERT INTO @TBLTICKET
(
    IDTICKET,
	IDCAMPANIA,
    RUCEMISOR,
    FECHAEMISION,
    TIPO,
    SERIE,
    NUMERO,
    CODIGOCLIENTE,
    NUMEROTK
)
SELECT t.IDTICKET, t.IDCAMPANIA,t.RUCEMISOR, t.FECHAEMISION,t.TIPOCOMPROBANTE,t.SERIECOMPROBANTE,t.NUMEROCOMPROBANTE,t.CODIGOCLIENTE,t.NUMEROTICKET
FROM dbo.TICKET t WHERE COALESCE(t.HOSTING,0) = 0



SELECT @MIN = MIN(t.INDICE) FROM @TBLTICKET t
SELECT @MAX = MAX(t.INDICE) FROM @TBLTICKET t

--SET @linkedserver = 'SMARTSOFT';
SET @linkedserver = 'TICKETS';
SET @openquery = 'SELECT rucEmisor FROM OPENQUERY(' + @linkedserver + ', ''';
SET @insertquery = 'INSERT INTO OPENQUERY(' + @linkedserver + ', ''';
SET @tsqlI1 = 'select idTicket, idEmpresa, idCampania, rucEmisor, fechaEmision, tipoComprobante, serieComprobante, numeroComprobante, codigoCliente, numeroTicket from TICKET'')';
--SELECT * FROM DBSRVHIELOSCLOUD.dbo.TICKET t
/*
USP_TICKET_SYNC
*/

WHILE @MIN <= @MAX
BEGIN

	SELECT TOP 1 @IDTICKET = t.IDTICKET,@IDCAMPANIA = t.IDCAMPANIA,  @RUCEMISOR = t.RUCEMISOR, @FECHAEMISION = t.FECHAEMISION, @TIPOCOMPROBANTE = t.TIPO, @SERIECOMPROBANTE = t.SERIE,
	@NUMEROCOMPROBANTE = NUMERO, @CODIGOCLIENTE = t.CODIGOCLIENTE, @NUMEROTICKET = t.NUMEROTK FROM @TBLTICKET t WHERE t.INDICE = @MIN;

	SET @tsql = 'select RUCEMISOR from TICKET where idempresa = ' + CAST(@IDEMPRESA AS VARCHAR(10)) + ' AND NUMEROTICKET =''''' + @NUMEROTICKET + ''''''')';
	--SELECT @IDTICKET, @NUMEROTICKET
	INSERT INTO @TBLVALIDA
	(
	    RUCEMISOR
	)
	EXEC (@openquery + @tsql);

	IF NOT EXISTS(SELECT TOP 1 'X' FROM @TBLVALIDA t)
	BEGIN

	--SELECT @IDTICKET, @RUCEMISOR, @FECHAEMISION, @TIPOCOMPROBANTE
	    SET @tsqlI2= ' select ' + CAST(@IDTICKET AS VARCHAR(20))+ ',' + CAST(@IDEMPRESA AS VARCHAR(20)) + ',' + CAST(@IDCAMPANIA AS VARCHAR(20)) +  ', ''' + @RUCEMISOR + ''', ''' + CONVERT(CHAR(8),@FECHAEMISION,112)+ ''',''' 
					+ @TIPOCOMPROBANTE + ''',''' + RIGHT('000' + @SERIECOMPROBANTE,3) + ''',' + CAST(@NUMEROCOMPROBANTE AS VARCHAR(20)) + ',' + CAST(@CODIGOCLIENTE AS VARCHAR(20))+ ',''' + @NUMEROTICKET + '''';

		EXEC (@insertquery + @tsqlI1 + @tsqlI2);
		--SELECT @insertquery + @tsqlI1 + @tsqlI2;

		UPDATE dbo.TICKET SET HOSTING = 1 WHERE IDTICKET = @IDTICKET AND IDCAMPANIA = @IDCAMPANIA AND TIPOCOMPROBANTE = @TIPOCOMPROBANTE AND SERIECOMPROBANTE = @SERIECOMPROBANTE
		AND NUMEROCOMPROBANTE = @NUMEROCOMPROBANTE;

		--SELECT * FROM dbo.TICKET t
	END
	ELSE
	--BEGIN
	--    SELECT 'EXISTE'
	--END

	DELETE FROM @TBLVALIDA

    SET @MIN = @MIN + 1
END



GO