ALTER TABLE dbo.PRODUCTO_PROMOCION ADD FECINI DATE DEFAULT NULL;
ALTER TABLE dbo.PRODUCTO_PROMOCION ADD FECFIN DATE DEFAULT NULL;
ALTER TABLE dbo.PRODUCTO_BONIFICACION ADD FECINI DATE DEFAULT NULL;
ALTER TABLE dbo.PRODUCTO_BONIFICACION ADD FECFIN DATE DEFAULT NULL;
ALTER TABLE dbo.PRODUCTO_PROMOCION_LOG ADD FECINI DATE;
ALTER TABLE dbo.PRODUCTO_PROMOCION_LOG ADD FECFIN DATE;
ALTER TABLE dbo.PRODUCTO_BONIFICACION_LOG ADD FECINI DATE;
ALTER TABLE dbo.PRODUCTO_BONIFICACION_LOG ADD FECFIN DATE;