IF EXISTS
(
    SELECT TOP 1
           s.SPECIFIC_NAME
    FROM INFORMATION_SCHEMA.ROUTINES s
    WHERE s.ROUTINE_TYPE = 'PROCEDURE' -- Validación del tipo
          AND ROUTINE_SCHEMA = 'dbo' -- Validación del esquema
          AND s.ROUTINE_NAME = 'USP_PROMOCION_BONIFICACION_FILL'
) -- Validación del nombre
BEGIN
    DROP PROC [dbo].[USP_PROMOCION_BONIFICACION_FILL];
END;
GO
/*
exec [dbo].[USP_PROMOCION_BONIFICACION_FILL] '01',2763
exec [dbo].[USP_PROMOCION_BONIFICACION_FILL] '01',2549
*/
CREATE PROCEDURE [dbo].[USP_PROMOCION_BONIFICACION_FILL]
    @CODCIA CHAR(2),
    @IDPRODUCTO BIGINT
WITH ENCRYPTION
AS
SET NOCOUNT ON;

SELECT ap.IDPRECIO AS idepre,
       RTRIM(LTRIM(ap.DESCRIPCION)) AS descripcion,
       ap.RNG_INI AS ini,
       COALESCE(ap.RNG_FIN, 0) AS fin,
       ap.PRECIO AS pre
	   ,CONVERT(CHAR(10),ap.FECINI,103) AS vigini
	   ,CONVERT(CHAR(10),ap.FECFIN,103) AS vigfin
FROM dbo.PRODUCTO_PROMOCION ap WITH (NOLOCK)
WHERE ap.CODCIA = @CODCIA
      AND ap.IDPRODUCTO = @IDPRODUCTO
ORDER BY ap.IDPRECIO;

SELECT ab.IDBONIFICACION AS idboni,
       RTRIM(LTRIM(a.ART_NOMBRE)) AS producto,
       ab.CANTIDAD AS cant,
       ab.BONIFICACION AS boni,
       ab.PRECIO AS pre,
       COALESCE(CAST(ab.TOPE AS VARCHAR(20)), '') AS tope
	   ,CONVERT(CHAR(10),ab.FECINI,103) AS vigini
	   ,CONVERT(CHAR(10),ab.FECFIN,103) AS vigfin
FROM dbo.PRODUCTO_BONIFICACION ab WITH (NOLOCK)
    INNER JOIN dbo.ARTI a
        ON ab.CODCIA = a.ART_CODCIA
           AND ab.IDBONIFICACION = a.ART_KEY
WHERE ab.CODCIA = @CODCIA
      AND ab.IDPRODUCTO = @IDPRODUCTO;

GO